### ISSUE TITLE
MAC address changes every time I recycle power 

### ISSUE THREAD

**Issue by rvinayak** [dspsandbox/Pynq-Redpitaya-125#1]
MAC address changes every time I recycle power  and a new random MAC address is assigned.

The router then assigns a new IP address every time.

Looks like  u-boot does not configure the MAC address of the network interface.

Could you please help?

Thanks,
Rohit

**Comment by dspsandbox** [comment]
Hello,
yes, this is expected because I did not configure the linux kernel to load the MAC address from the on-board EEPROM. In the following months I will launch a new PYNQ image build to circumvent this limitation. 

In the meantime, you can re-assign the mac address via software: 
```
echo xilinx | sudo -S ip link set dev eth0 down
echo xilinx | sudo -S ip link set dev eth0 address XX:XX:XX:XX:XX:XX
echo xilinx | sudo -S ip link set dev eth0 up
```
where XX:XX:XX:XX:XX:XX is the mac address of your choice. 

You can automate the process by editing the boot.py file (within the pynq partition of your SD card), which is always executed after boot. I am a showing below an example of this:
```
import os
import time
cmd_list = []
cmd_list.append("echo xilinx | sudo -S ip link set dev eth0 down")
cmd_list.append("echo xilinx | sudo -S ip link set dev eth0 address XX:XX:XX:XX:XX:XX")
cmd_list.append("echo xilinx | sudo -S ip link set dev eth0 up")
for cmd in cmd_list:
    os.system(cmd)
```
I hope this helps.

Cheers,
Pau

**Comment by rvinayak** [comment]
Many thanks Pau.

I ended up writing directly to the /etc/network/interfaces.d/eth0 file.

Looking forward to the new build.

Thanks,

Rohit


On 23-May-2022, at 8:19 PM, Pau Gómez ***@***.******@***.***>> wrote:



Hello,
yes, this is expected because I did not configure the linux kernel to load the MAC address from the on-board EEPROM. In the following months I will launch a new PYNQ image build to circumvent this limitation.

In the meantime, you can re-assign the IP address via software:

echo xilinx | sudo -S ip link set dev eth0 down
echo xilinx | sudo -S ip link set dev eth0 address XX:XX:XX:XX:XX:XX
echo xilinx | sudo -S ip link set dev eth0 up


where XX:XX:XX:XX:XX:XX is the mac address of your choice.

You can automate the process by editing the boot.py file (within the pynq partition of your SD card), which is always executed after boot. I am a showing below an example of this:

import os
import time
cmd_list = []
cmd_list.append("echo xilinx | sudo -S ip link set dev eth0 down")
cmd_list.append("echo xilinx | sudo -S ip link set dev eth0 address XX:XX:XX:XX:XX:XX")
cmd_list.append("echo xilinx | sudo -S ip link set dev eth0 up")
for cmd in cmd_list:
    os.system(cmd)


I hope this helps.

Cheers,
Pau
